### ISSUE TITLE
Opening banner text missing opportunity for maximum impact

### ISSUE THREAD

**Issue by LiteBit** [particl/particl.io#35]
After we launched the website one of the hot topics within the community channels was the opening message in the banner. 

> A decentralized platform with a native suite of tools to enhance and protect your online privacy

This space was always invisioned as the spot for us to give a simple statement as to what we're about. Not to focus on the currency or utility but on the platform as a whole and summarize the vision of the project. 

The community had a lot of opinion's about the spot as it's the first thing a visitor sees. One of the most productive critiques was from "kaspr" pointing out that this should be the spot we highlight our main attraction, the Particl Marketplace. I think it's a valid point. 

> The world's most private marketplace

Directly below this spot we talk about the "why" and then "how", so we'd lose the "what" part of the story first off, but there's possibly a way to still get that across with some min tweaks to those 2 sections. 

Based on the initial proposed changing of the banner text by kaspr here is a first shot at identifying what that text should say. 
![image](https://user-images.githubusercontent.com/6236019/36972939-112ec480-203f-11e8-8db4-7dbeaef32077.png)

Let's use this issue as the container for this topic.

**Comment by joefiorello** [comment]
I agree about the banner text.  Sell the product.  It's what will bring people to part.  I would also highlight cold staking and the passive income potential around holding a large stake in Particl.

**Comment by LiteBit** [comment]
We had a couple suggestions for 

> Decentralized Applications Focused on Privacy

Which was shortened to 

> Privacy Focused Decentralized Applications

**Comment by LiteBit** [comment]
![image](https://user-images.githubusercontent.com/6236019/36998224-2aa3bba0-208a-11e8-8657-abf6e57aba64.png)

That might be the winner there

**Comment by kasprrr** [comment]
For the love of the crypto gods, please consider the following:

The current headline sucks for the purpose it's there for; grabbing the visitor's attention, while leaving a noticeable/memorable impression of the project **and provoking somewhat of an emotional response**). I understand you wish to describe all things PART is in a single headline. However, the current headline is to ambiguous, complex and will only promote confusion. It will accomplish the opposite of what you are trying to do, communicating why PART is awesome. Instead of trying to be all this, pick and choose your flagship product...

I like "Privacy Focused Decentralized applications", but i really like to see the marketplace being actively promoted as a headline first. Not solely on a separate page like _marketplace.particl.io_ as suggested. Of course, such strategy can be changed later on.

The marketplace is literally the first DAPP on the platform and has been in development for over 3 years. It's what most of the community has been waiting for. It is also something the world understands, and if PART wants to be a platform used by the average Joe, your headline needs to be understood by non-tech/non crypto savvy people. You have only one chance of making an impression mostly, and a game theory optimal strategy would be to use a headline which grabs the most attention. 

I still suggest going in the direction of something like **"PART: the world's most private marketplace"**.
Or at least rotate the text (and perhaps have one or two more headlines) but use this marketplace reference as your first headline). 

It could be nice to have a click-through to screenshots of the marketplace, marketplace.particl.io or incorporate screenshots in the background in a way its not making the headline less conspicuous or readable. I like the current image behind the headline, but it makes the headline somewhat less readable, so consider tweaking its position/size/color a little bit. You may also choose to use a simple but catchy animation (in the current corporate identity/graphic style) as a headline instead of a rotator. _If you ever consider doing animations, i'd recommend the guy that did animations for ETH DAPP Kibo: https://kiboplatform.net/en/landing.html or make use of very simple but catchy animations in html5 such as the ones on https://www.ethereum.org/_ 

Please team, make this community grow and start actively promoting this marketplace launch.
Thanks for your consideration.

and for the rest, everyone's doing an awesome job.
greeting, kapsr (lost passw. from other github acc. sigh)

**Comment by rustypart** [comment]
- Worlds Most Private Marketplace -
Have no words before it or after it.  It makes a very bold statement that even kids will understand, we have to cut to the chase and this is the only sentence that reasonably describes Particl in just 4 words.

**Comment by LiteBit** [comment]
@kasprrr @rustypart thanks for adding these comments

I like World's Most Private Marketplace too. If we did that we'd need to say "we're building the world's..." or "At Particl, we're building..." because while it promotes the marketplace it negates all the other things Part is. Adding "we're building" would at least hint at this is one of the cool things we're doing

> PART: the world's most private marketplace 

That doesn't work imho because PART is our currency not our marketplace. So you're confusing everyone right off the bat.

For now I have a pull request to immediately fix the current one to "Privacy Focused Decentralized Applications" #39 
However, I'll leave this open for more discussion. Nothing saying that's final, everyone does seem to agree it's at least better than the current one.

We'll also look at options for rotating text. Good suggestion

**Comment by cryptoguard** [comment]
While I agree more emphasis could be put on the marketplace aspect of the project, the first sentence should be a description of what the project is as a whole. It's true that the marketplace was once the sole product being worked on of Shadowcash, but the project has grown a lot since and its vision has evolved so I believe the first sentence should reflect this new vision. I also believe this sentence should always stay the same throughout the life of this project, changing it every time shows a lack of vision. 

I am, however, a fan of creating a marketplace.particl.io page and have it dedicated solely to the marketplace. In there, we can put **Particl: The World's Most Private Marketplace** and have a ton of stuff as it relates to the marketplace (videos, screenshots, listings, tutorials, etc), but again, I really believe the particl.io main page should be focused on the platform we are building rather than on the marketplace. Doing so would be too narrow minded and frankly negates everything else that's being done on the platform. We need our vision to be clear and always the same even after we release tens of DApps. 

On another note, I would propose maybe tweaking **Privacy Focused Decentralized Applications**  to **A Platform For Privacy Focused Decentralized Applications**. The reason why is because of how the marketplace and future Dapps are going to be integrated (within Particl Desktop itself). So it makes sense to highlight our platform (Particl Desktop) rather than simply highlighting the Dapps. In other words, **Privacy Focused Decentralized Applications** makes me think more of an Ethereum-style Dapp blockchain where Dapps are all over the place while **A Platform For Privacy Focused Decentralized Applications** makes it clear that the Dapps are hosted within a platform. At the least, it does a better job at conveying the message that we are a platform and not just some Dapp blockchain like Ethereum, Lisk, etc.

**Comment by kasprrr** [comment]
"Building the world's most private marketplace", i like.

Please consider this to be on the main page somewhere, next to or in small light gray below "Privacy Focused Decentralized Application". Or again, use it for marketplace marketing, and there should be references to the upcoming marketplace on PAGE 1 on particl.io (main site), visible for the visitor without having to scroll down first. Is the team planning to market the upcoming release on their main site? if not that would be a horrible decision imho.

@cryptoguard 
"Privacy Focused Decentralized Application" works a heck of a lot better then "A Platform For Privacy Focused Decentralized Applications" Cryptoguard. You need to understand that a headline is not  designed to include all the information, but for all the other reasons i mentioned earlier in my first post.

**Comment by cryptoguard** [comment]
@kasprrr Curious to hear why you think "Privacy Focused Decentralized Application" works better than "A Platform For Privacy Focused Decentralized Applications". My personal impression is that Particl is better defined by the latter rather than the former. I don't think it adds confusion as to what Particl is, only makes it clearer?  

What about adding an additional button next to "Why Particl" under the headline (no scrolling) or in the header next to Download Particl Desktop (this way, whenever you scroll the link stays visible) that links to the marketplace.particl.io page?

Obviously, one of the solution would be to put some rotating texts. We could have the headline about the platform, about the marketplace, and one each for the subsequent Dapps. One thing that could be cool also would be to keep the headline about the Dapps/platform, and then have under it rotating images accompanied by a quote (one for each Dapp). So for the example of the marketplace, we could have some screenshot of it within a circle or something and have the quote **World's Most Private Marketplace** under it. 

Now at first it probably wouldn't be rotating with anything else so we could find a way to make that static, but I'm hearing through the grapevines there are already people looking into building stuff on Particl so with the SDK coming that rotating feature would be nice as a showcase for all DApps built or being built.

**Comment by cryptoguard** [comment]
Additional suggestion from DumboTheDumbo on Reddit which I like quite a lot: **Decentralized Marketplace & Applications Focused On Privacy**. Seems to be a good way to address both the platform and marketplace side of things?

**Comment by GeorgeMoroz** [comment]
I'm curious of what people think of my idea. I am here to help discuss and brainstorm.

**Comment by LiteBit** [comment]
> A decentralized platform with a native suite of tools to enhance and protect your online privacy

I will say that this original text answers the **What** (A decentralized platform), **Why** (enhance and protect your online privacy) and **How** (native suite of tools) in one sentence. 

As I'm creating a powerpoint for an upcoming meetup this helps talk about Particl in one slide versus a bunch of slide.

fwiw

**Comment by AllienWorks** [comment]
> @LiteBit A decentralized platform with a native suite of tools to enhance and protect your online privacy

I like that, however I feel it's a bit too long for this text. I would like to shorten it to:

> A decentralized dApp platform to enhance and protect your online privacy

..where none of the message is missing (from my POV) and it's still fast to read and easy to understand.

**Comment by GeorgeMoroz** [comment]
If you guys are not going to include the word marketplace in the tagline, I sure hope there is a big section right below that focuses solely on the marketplace.

**Comment by cryptoguard** [comment]
I noticed we have used "Privacy-Focused Marketplace and Privacy Platform" for our new social media banner, can we use the same tagline for the website (at least so it is consistent throughout all of our platforms).

**Comment by AllienWorks** [comment]
Current intro text

> Privacy Focused Decentralized Applications

changed to

> Privacy-Focused Marketplace & Decentralized Application Platform

If there's consensus about another update, we can change it again (no problem). I will be closing this issue, but you can re-open it and continue discussing if needed.
